# Generated by Django 5.0 on 2023-12-27 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens/%Y/%m/')),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
                ('reacao', models.PositiveIntegerField(default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legenda', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens/%Y/%m/')),
                ('data_postagem', models.DateTimeField(auto_now_add=True)),
                ('reacao', models.PositiveIntegerField(default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comentario', models.ManyToManyField(to='post.comentario')),
            ],
        ),
    ]
